CREATE TABLE [dbo].[Utilisateur]
(
	[Id] INT NOT NULL IDENTITY,
	[Username] NVARCHAR(255) NOT NULL,
	[Email] NVARCHAR(255) NOT NULL,
	[Password] VARBINARY(64) NOT NULL,
	[Salt] VARCHAR(50) NOT NULL,

	CONSTRAINT PK_UTILISATEUR_ID PRIMARY KEY (Id),
	CONSTRAINT UK_UTILISATEUR_USERNAME UNIQUE (Username),
	CONSTRAINT UK_UTILISATEUR_EMAIL UNIQUE (Email),
	CONSTRAINT CK_UTILISATEUR_EMAIL CHECK (Email LIKE '%@%.%')
)
